FROM node:20

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}
ARG API_URL
ENV API_URL=${API_URL}

WORKDIR /app

# Install deps first to cache properly
COPY package.json package-lock.json* ./
RUN npm install

# Source mounted at runtime
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
