name: "CI/CD Backend"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/ellismcdougald/edmonton-bike-backend
      IMAGE_TAG: latest

    steps:
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run tests
        run: go test ./...
        working-directory: backend

      - name: Build Docker image
        run: docker build --progress=plain -f backend/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG backend/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Run backend playbook
        run: ansible-playbook backend.yml -i inventory.ini --private-key ~/.ssh/id_rsa -e "ghcr_pat=${{ secrets.GITHUB_TOKEN }}"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          LE_EMAIL: ${{ secrets.LE_EMAIL }}
        working-directory: deployment/ansible
