name: Weekly Database Update

on:
  schedule:
    - cron: "0 3 * * 0" # Every Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Run backend playbook
        run: ansible-playbook update-db.yml -i inventory.ini --private-key ~/.ssh/id_rsa -e "ghcr_pat=${{ secrets.GHCR_PAT }}"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          LE_EMAIL: ${{ secrets.LE_EMAIL }}
        working-directory: deployment/ansible
